### ISSUE TITLE
播放本地mp4文件失败

### ISSUE THREAD

**Issue by a1154043439** [zxfrdas/LocalSocketMediaProxy#1]
你好，我尝试运行模拟器本地的mp4文件，报下面的错，不知道你有没有遇到这种问题。
08-09 03:03:10.210 11000-11000/com.example.vedioviewdemo W/System.err: java.io.IOException: Prepare failed.: status=0x1
08-09 03:03:10.210 11000-11000/com.example.vedioviewdemo W/System.err:     at android.media.MediaPlayer._prepare(Native Method)
08-09 03:03:10.210 11000-11000/com.example.vedioviewdemo W/System.err:     at android.media.MediaPlayer.prepare(MediaPlayer.java:1163)
08-09 03:03:10.210 11000-11000/com.example.vedioviewdemo W/System.err:     at com.example.vedioviewdemo.MainActivity.play(MainActivity.java:75)

**Comment by a1154043439** [comment]
补充说明:
private void openFileChannel() throws FileNotFoundException {
        if (null == fileChannel) {
            File test = new File("/storage/emulated/0/demo.mp4");
            fileChannel = new RandomAccessFile(test, "r").getChannel();
        }
    }
文件路径是确认有效的，而且mp4文件是完整的可以播放的，除了路径之外，并没有修改你的代码。

**Comment by a1154043439** [comment]
找到原因了，是我忘记在manifest里面注册service了,汗！最近也在研究Android边下边播，可以一起交流吗？

**Comment by zxfrdas** [comment]
哦哦哦。解决了就好，欢迎各种交流 XD
